backend:
  name: git-gateway
  branch: main # أو اسم الفرع الذي تستخدمينه
media_folder: "static/uploads" # المجلد الذي ستخزن فيه الصور والملفات
public_folder: "/uploads" # المسار للوصول للصور

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog" # المجلد الذي يحتوي على المقالات
    create: true # السماح بإنشاء مقالات جديدة
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }
